# PingClass Staging Setup Script
# Run this AFTER creating the Supabase staging branch

Write-Host "`n=== PingClass Staging Setup ===" -ForegroundColor Cyan

# 1. Get staging branch details
Write-Host "`n1. Go to Supabase Dashboard -> Branches -> staging" -ForegroundColor Yellow
Write-Host "   Copy the branch URL and anon key from Settings -> API" -ForegroundColor Gray

$branchUrl = Read-Host "Paste staging branch URL (e.g. https://xxxxx.supabase.co)"
$branchKey = Read-Host "Paste staging branch anon key"

if (-not $branchUrl -or -not $branchKey) {
    Write-Host "ERROR: Both URL and key are required" -ForegroundColor Red
    exit 1
}

# 2. Update config.js with staging values
$configContent = @"
// PingClass Config — STAGING (auto-generated by setup-staging.ps1)
const CONFIG = {
  RAZORPAY_KEY_ID: 'rzp_test_TA9d1aYSVLeGFh',
  SUPABASE_URL: '$branchUrl',
  SUPABASE_ANON_KEY: '$branchKey',
  PLANS: {
    free: { name: 'Free', amount: 0, razorpayPlanId: null },
    basic: { name: 'Basic', amount: 24900, razorpayPlanId: null },
    pro: { name: 'Pro', amount: 59900, razorpayPlanId: null }
  }
};
"@

Set-Content -Path "config.js" -Value $configContent -Encoding UTF8
Write-Host "`n2. config.js updated with staging credentials" -ForegroundColor Green

# 3. Check if git is initialized
if (Test-Path ".git") {
    Write-Host "`n3. Git repo detected. Ready to push." -ForegroundColor Green
} else {
    Write-Host "`n3. Initializing git repo..." -ForegroundColor Yellow
    git init
    git add -A
    git commit -m "Initial commit"
    Write-Host "   Git repo initialized" -ForegroundColor Green
}

Write-Host "`n=== Next Steps ===" -ForegroundColor Cyan
Write-Host "1. Push to GitHub:" -ForegroundColor Yellow
Write-Host "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git" -ForegroundColor Gray
Write-Host "   git push -u origin main" -ForegroundColor Gray
Write-Host ""
Write-Host "2. Deploy to Vercel:" -ForegroundColor Yellow
Write-Host "   - Go to vercel.com" -ForegroundColor Gray
Write-Host "   - Import your GitHub repo" -ForegroundColor Gray
Write-Host "   - Framework: Other" -ForegroundColor Gray
Write-Host "   - Deploy" -ForegroundColor Gray
Write-Host ""
Write-Host "3. After deploy, note the Vercel URL (e.g. pingclass.vercel.app)" -ForegroundColor Yellow
Write-Host "   You'll need it for Strix scanning." -ForegroundColor Gray
Write-Host ""
Write-Host "4. Restore production config.js when done:" -ForegroundColor Yellow
Write-Host "   git checkout config.js" -ForegroundColor Gray
